import React from "react";
export const metadata = {
  title: "add product dashboard| Hotel Management",
  description: "Generated by create next app",
};

const AddProduct = () => {
  return <div>product added page</div>;
};

export default AddProduct;
