import React from "react";
export const metadata = {
  title: "About | Hotel Management",
  description: "Generated by create next app",
};

const Departments = () => {
  return <div>about page</div>;
};

export default Departments;
